# Generated by Django 4.2.6 on 2023-10-15 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='user_password',
            field=models.CharField(default=datetime.date, max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
