# Generated by Django 4.2.6 on 2023-10-15 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hw2', '0002_client_user_password_alter_client_registration_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user_password',
        ),
    ]
